<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="2" failures="0" file="test_python_simulation.py"
           name="test_python_simulation.TestPythonSimulation-20190807195348" skipped="0" tests="2" time="77.813"
           timestamp="2019-08-07T19:56:03">
    <testcase classname="test_python_simulation.TestPythonSimulation" file="test_python_simulation.py" line="64"
              name="test_add_prefixed_relative_path_to_assets_local" time="41.056" timestamp="2019-08-07T19:55:26">
        <error message="CreateSimulationTask('IGSUD42G', {'a': 0})" type="ResultTimeout">
            <![CDATA[Traceback (most recent call last):
  File "/home/clinton/development/work/idmtools/idmtools_platform_local/tests/test_python_simulation.py", line 89, in test_add_prefixed_relative_path_to_assets_local
    em.run()
  File "/home/clinton/development/work/idmtools/idmtools_core/idmtools/managers/ExperimentManager.py", line 95, in run
    self.create_simulations()
  File "/home/clinton/development/work/idmtools/idmtools_core/idmtools/managers/ExperimentManager.py", line 74, in create_simulations
    for sim_batch in results:
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/clinton/development/work/idmtools/idmtools_core/idmtools/managers/ExperimentManager.py", line 56, in simulation_batch_worker_thread
    ids = self.platform.create_simulations(simulation_batch)
  File "/home/clinton/development/work/idmtools/idmtools_platform_local/idmtools_platform_local/local_platform.py", line 155, in create_simulations
    sid = m.get_result(block=True, timeout=self.default_timeout * 1000)
  File "/home/clinton/.virtualenvs/idmtools/lib/python3.7/site-packages/dramatiq/message.py", line 147, in get_result
    return backend.get_result(self, block=block, timeout=timeout)
  File "/home/clinton/.virtualenvs/idmtools/lib/python3.7/site-packages/dramatiq/results/backends/redis.py", line 81, in get_result
    raise ResultTimeout(message)
dramatiq.results.errors.ResultTimeout: CreateSimulationTask('IGSUD42G', {'a': 0})
]]>        </error>
        <system-out>
            <![CDATA[[Local_Staging]: the following Config Settings are not used:
 - extra1 = 1
 - extra2 = 2

[K]]>        </system-out>
        <system-err>
            <![CDATA[]]>        </system-err>
    </testcase>
    <testcase classname="test_python_simulation.TestPythonSimulation" file="test_python_simulation.py" line="27"
              name="test_direct_sweep_one_parameter_local" time="36.757" timestamp="2019-08-07T19:56:03">
        <error message="CreateSimulationTask('ZDJEA8PE', {'a': 0})" type="ResultTimeout">
            <![CDATA[Traceback (most recent call last):
  File "/home/clinton/development/work/idmtools/idmtools_platform_local/tests/test_python_simulation.py", line 44, in test_direct_sweep_one_parameter_local
    em.run()
  File "/home/clinton/development/work/idmtools/idmtools_core/idmtools/managers/ExperimentManager.py", line 95, in run
    self.create_simulations()
  File "/home/clinton/development/work/idmtools/idmtools_core/idmtools/managers/ExperimentManager.py", line 74, in create_simulations
    for sim_batch in results:
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/clinton/development/work/idmtools/idmtools_core/idmtools/managers/ExperimentManager.py", line 56, in simulation_batch_worker_thread
    ids = self.platform.create_simulations(simulation_batch)
  File "/home/clinton/development/work/idmtools/idmtools_platform_local/idmtools_platform_local/local_platform.py", line 155, in create_simulations
    sid = m.get_result(block=True, timeout=self.default_timeout * 1000)
  File "/home/clinton/.virtualenvs/idmtools/lib/python3.7/site-packages/dramatiq/message.py", line 147, in get_result
    return backend.get_result(self, block=block, timeout=timeout)
  File "/home/clinton/.virtualenvs/idmtools/lib/python3.7/site-packages/dramatiq/results/backends/redis.py", line 81, in get_result
    raise ResultTimeout(message)
dramatiq.results.errors.ResultTimeout: CreateSimulationTask('ZDJEA8PE', {'a': 0})
]]>        </error>
        <system-out>
            <![CDATA[[Local_Staging]: the following Config Settings are not used:
 - extra1 = 1
 - extra2 = 2

[K]]>        </system-out>
        <system-err>
            <![CDATA[]]>        </system-err>
    </testcase>
</testsuite>
